service:
  name: pubmed-manager

# Add the serverless-webpack plugin
plugins:
- serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  search:
    handler: src/search/handler.search
    events:
    - http:
        method: get
        path: publications
  details:
    handler: src/details/handler.getPublicationDetails
    events:
    - http:
        method: get
        path: publications/{id}
  postFavorite:
    handler: src/saveFavorite/handler.saveFavorite
    events:
    - http:
        method: post
        path: favorites